# Default configuration for MedMT
train_data: data/train.csv
test_data: data/test.csv
submission_sample: data/sample_submission.csv
model_save_path: models/MedicalZbitxLM
output_dir: outputs/
pretrained_model: "XiaoduoAILab/XmodelLM1.5" # Using XiaoduoAILab/XmodelLM1.5 as the base
max_seq_length: 256
batch_size: 16 # Adjust based on your GPU memory
epochs: 5 # Adjust as needed
learning_rate: 3e-5 # Adjust as needed
use_context: true
